FROM lsiobase/alpine.python.armhf

LABEL maintainer="tzinm" \
      version="1.0" \
      system="arm"

WORKDIR /home/

COPY AddToQbitTorrentFolder.py .

RUN \
 pip install --upgrade pip && \
 python -m pip install telegram --upgrade && \
 python -m pip install python-telegram-bot --upgrade && \
 chown root:root AddToQbitTorrentFolder.py && \
 chmod 644 AddToQbitTorrentFolder.py && \
 mkdir /zip/ && \
 mkdir descargas

VOLUME /home/descargas

CMD ["python", "/home/AddToQbitTorrentFolder.py"]
